// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_deliveryBoyProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_deliveryBoyProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202405121529255_added_deliveryBoyProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
