// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class str_pk_chat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(str_pk_chat));
        
        string IMigrationMetadata.Id
        {
            get { return "202405131657169_str_pk_chat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
